// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Destino struct {
	ID          int32
	NombreLugar string
	FechaViaje  time.Time
	Valoracion  sql.NullInt32
	Descripcion sql.NullString
	CreatedAt   sql.NullTime
}
