// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createDestino = `-- name: CreateDestino :one
INSERT INTO destinos (nombre_lugar, fecha_viaje, valoracion, descripcion)
VALUES ($1, $2, $3, $4)
RETURNING id, nombre_lugar, fecha_viaje, valoracion, descripcion, created_at
`

type CreateDestinoParams struct {
	NombreLugar string
	FechaViaje  time.Time
	Valoracion  sql.NullInt32
	Descripcion sql.NullString
}

func (q *Queries) CreateDestino(ctx context.Context, arg CreateDestinoParams) (Destino, error) {
	row := q.db.QueryRowContext(ctx, createDestino,
		arg.NombreLugar,
		arg.FechaViaje,
		arg.Valoracion,
		arg.Descripcion,
	)
	var i Destino
	err := row.Scan(
		&i.ID,
		&i.NombreLugar,
		&i.FechaViaje,
		&i.Valoracion,
		&i.Descripcion,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDestino = `-- name: DeleteDestino :exec
DELETE FROM destinos WHERE id = $1
`

func (q *Queries) DeleteDestino(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteDestino, id)
	return err
}

const getDestino = `-- name: GetDestino :one
SELECT id, nombre_lugar, fecha_viaje, valoracion, descripcion, created_at FROM destinos WHERE id = $1
`

func (q *Queries) GetDestino(ctx context.Context, id int32) (Destino, error) {
	row := q.db.QueryRowContext(ctx, getDestino, id)
	var i Destino
	err := row.Scan(
		&i.ID,
		&i.NombreLugar,
		&i.FechaViaje,
		&i.Valoracion,
		&i.Descripcion,
		&i.CreatedAt,
	)
	return i, err
}

const listDestinos = `-- name: ListDestinos :many
SELECT id, nombre_lugar, fecha_viaje, valoracion, descripcion, created_at FROM destinos ORDER BY fecha_viaje DESC
`

func (q *Queries) ListDestinos(ctx context.Context) ([]Destino, error) {
	rows, err := q.db.QueryContext(ctx, listDestinos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Destino
	for rows.Next() {
		var i Destino
		if err := rows.Scan(
			&i.ID,
			&i.NombreLugar,
			&i.FechaViaje,
			&i.Valoracion,
			&i.Descripcion,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDestino = `-- name: UpdateDestino :exec
UPDATE destinos 
SET nombre_lugar = $2, fecha_viaje = $3, valoracion = $4, descripcion = $5 
WHERE id = $1
`

type UpdateDestinoParams struct {
	ID          int32
	NombreLugar string
	FechaViaje  time.Time
	Valoracion  sql.NullInt32
	Descripcion sql.NullString
}

func (q *Queries) UpdateDestino(ctx context.Context, arg UpdateDestinoParams) error {
	_, err := q.db.ExecContext(ctx, updateDestino,
		arg.ID,
		arg.NombreLugar,
		arg.FechaViaje,
		arg.Valoracion,
		arg.Descripcion,
	)
	return err
}
